### ISSUE TITLE
a compile error

### ISSUE THREAD

**Issue by zglx2008** [albfan/systemd-ubuntu-with-dbus#3]
when compile,the following errors are encountered

```
==== test-verbs.log ====
Unknown operation command-not-found.
Too few arguments.
Too many arguments.
Requires operation parameter.
==== test-xml.log ====
debian/rules:251: recipe for target 'override_dh_auto_test' failed    
make[1]: *** [override_dh_auto_test] Error 1
make[1]: Leaving directory '/home/zglx2008/CodeBuild/systemd-ubuntu-with-dbus-master0'
debian/rules:262: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc -i failed
```

**Comment by albfan** [comment]
See problematic line:

[debian/rules:250](https://github.com/albfan/systemd-ubuntu-with-dbus/blob/89899b365a4fa7f0f60f561430c817666296fa55/debian/rules#L250)

in previous conversations with upstream ubuntu maintainers, they told me they disable a lot of tests from its upstream project (freedesktop) to build systemd, so maybe is ok to add

```
$ export DEB_BUILD_OPTIONS=nocheck
```

Before `dpkg-buildpackage`

For me it's scary option, because you can break you startup.

Your best aproach is to go to this page:

https://anonscm.debian.org/cgit/pkg-systemd/systemd.git

and find the tag that matches your system "ubuntu/xxx-x" an reapply this 

https://github.com/albfan/systemd-ubuntu-with-dbus/commit/51439fccfbea02bc266a650e52d82a4ee1308eb6#diff-d2b2229a977ef7e99780f2207c29b503R48

you can fetch from this repo (since it is a clone) and send a PR
